# Generated by Django 4.1.7 on 2023-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_productvariantmetadata_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariantmetadata",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="productvariantcombination",
            name="price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productvariantcombination",
            name="sku",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name="colorvariant",
            constraint=models.UniqueConstraint(
                fields=("product_variant_metadata", "color_name"),
                name="unique_together__color_variant__variant_metadata_color_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialvariant",
            constraint=models.UniqueConstraint(
                fields=("product_variant_metadata", "material_name"),
                name="unique_together__color_variant__variant_metadata_material_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariantmetadata",
            constraint=models.UniqueConstraint(
                fields=("variant_name", "product"),
                name="unique_together__color_variant__variant_metadata_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="sizevariant",
            constraint=models.UniqueConstraint(
                fields=("product_variant_metadata", "size_name"),
                name="unique_together__color_variant__variant_metadata_size_name",
            ),
        ),
    ]
